#!/bin/bash

# Echo + Hermes - Deployment Script
echo "🚀 Echo Deployment Guide"
echo "========================"
echo ""
echo "Your Echo landing page and documentation are ready!"
echo ""
echo "📁 Repository updated at:"
echo "   https://github.com/EstebanCastel/cluely-hermes"
echo ""
echo "To deploy to Vercel:"
echo ""
echo "Option 1: Deploy via Vercel Dashboard (Recommended)"
echo "   1. Go to https://vercel.com"
echo "   2. Sign in with your GitHub account"
echo "   3. Click 'Import Project'"
echo "   4. Import: https://github.com/EstebanCastel/cluely-hermes"
echo "   5. Click Deploy"
echo ""
echo "Option 2: Deploy via CLI"
echo "   1. Install Vercel CLI: npm i -g vercel"
echo "   2. Login: vercel login"
echo "   3. Deploy: vercel --prod"
echo ""
echo "Option 3: Use GitHub Pages"
echo "   1. Go to repository Settings"
echo "   2. Navigate to Pages"
echo "   3. Source: Deploy from branch"
echo "   4. Branch: main, folder: /docs"
echo "   5. Save and wait for deployment"
echo ""
echo "📄 Files created:"
echo "   • docs/index.html - Landing page"
echo "   • docs/INSTALLATION.md - Integration guide"
echo "   • README.md - Updated documentation"
echo "   • vercel.json - Vercel configuration"
echo ""
echo "✅ Everything is ready for deployment!"